media:
  input: assets
  output: assets

content:
  - name: products
    label: Products
    type: collection
    path: _data/products
    format: yaml
    extension: yml
    fields:
      - name: title
        label: Product Name
        type: string
        required: true
      - name: price
        label: Price Text
        type: string
        required: true
        default: "DM for Price"
      - name: description
        label: Description
        type: string
        required: true
      - name: image
        label: Product Image
        type: image
        required: true
