media:
  input: assets
  output: assets

content:
  - name: products
    label: Products
    type: collection
    path: _data/products
    format: yaml
    extension: yml
    filename: "{slug}.yml"
    fields:
      - name: product_id
        label: Product ID (e.g. LMS-006)
        type: string
        required: true
      - name: category
        label: Category
        type: select
        options:
          values:
            - label: Bag Charms
              value: Bag Charms
            - label: Fridge Magnets
              value: Fridge Magnets
            - label: Pin Badges
              value: Pin Badges
            - label: Pottery
              value: Pottery
            - label: Stamp Magnets
              value: Stamp Magnets
        required: true
      - name: title
        label: Item Name
        type: string
        required: true
      - name: price
        label: Price
        type: string
        required: true
        default: "DM for Price"
      - name: description
        label: Description
        type: string
        required: true
      - name: image
        label: Product Image
        type: image
        required: true
